# Generated by Django 6.0 on 2026-01-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-01'),
            preserve_default=False,
        ),
    ]
